# ------------------------------------- MDRC -------------------------------------

[discord]
[discord.MDRC_Discord]

# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# in particular that the "Members Intent" checkbox is important.
# If you want roles/groups mentions to be shown with names instead of ID, 
# you'll need to give your bot the "Manage Roles" permission.
Token="${MDRC_DISCORD}"

Server="997967607506407435" # picked from guilds the bot is connected to
AutoWebhooks=true

RemoteNickFormat="{BRIDGE} - @{NICK}"
# Map threads from other bridges on discord replies
PreserveThreading=true

[slack]
[slack.MDRC_Slack]
Token="${MDRC_SLACK}"
RemoteNickFormat="{BRIDGE} - @{NICK}"
# this will maps threads from other bridges on slack threads
PreserveThreading=true



# club
[[gateway]]
name="general"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="general"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="general"

[[gateway]]
name="random"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="random"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="random"




# eboard
[[gateway]]
name="eboard"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="eboard"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="eboard"

[[gateway]]
name="mural-planning-committee"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="mural-planning-committee"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="mural-planning-committee"

[[gateway]]
name="matterbridge-testing"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="matterbridge-testing"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="matterbridge-test"



# teams
[[gateway]]
name="3lb_battlebot"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="3lb_battlebot"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="3lb_battlebot"

[[gateway]]
name="12lb_battlebot"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="12lb_battlebot"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="12lb_battlebot"

[[gateway]]
name="30lb_battlebot"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="30lb_battlebot"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="30lb_battlebot"

[[gateway]]
name="pacbot"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="pacbot"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="pacbot-2020"

[[gateway]]
name="catbot"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="catbot"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="catbot"

[[gateway]]
name="couchbot"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="couchbot"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="couchbot"

[[gateway]]
name="urc"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="urc"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="urc"

[[gateway]]
name="ultima"
enable=true
[[gateway.inout]]
account="discord.MDRC_Discord"
channel="ultima"
[[gateway.inout]]
account="slack.MDRC_Slack"
channel="ultima"
